# Book Request
GET http://127.0.0.1:8000/author/author/65e85db7625742abec542ca1
Authorization:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoiNjVkYzliOTdjNzBiNWRjOTVjY2EwNWZlIiwibmFtZSI6IlRlc3QgMSIsImxvY2F0aW9uIjoiQ2hlbm5haSIsInRpdGxlIjoiREVWRUxPUEVSIHcifSwiaWF0IjoxNzEyMjEyMjAzLCJleHAiOjE3MTIyMTU4MDN9.sjWKCxedJPbHlUDMep2KlVmoQVa42CyvKzvj-Yrz6DU

### Authors

GET http://127.0.0.1:8000/author/authors
Authorization:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoiNjVkYzliOTdjNzBiNWRjOTVjY2EwNWZlIiwibmFtZSI6IlRlc3QgMSIsImxvY2F0aW9uIjoiQ2hlbm5haSIsInRpdGxlIjoiREVWRUxPUEVSIHcifSwiaWF0IjoxNzEyMjEyMjAzLCJleHAiOjE3MTIyMTU4MDN9.sjWKCxedJPbHlUDMep2KlVmoQVa42CyvKzvj-Yrz6DU

### fetch again
GET http://127.0.0.1:8000/author/authors
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoiNjVkYzliOTdjNzBiNWRjOTVjY2EwNWZlIiwibmFtZSI6IlRlc3QgMSIsImxvY2F0aW9uIjoiQ2hlbm5haSIsInRpdGxlIjoiREVWRUxPUEVSIHcifSwiaWF0IjoxNzEyMjEyMjAzLCJleHAiOjE3MTIyMTU4MDN9.sjWKCxedJPbHlUDMep2KlVmoQVa42CyvKzvj-Yrz6DU

### users authentication middleware
GET http://127.0.0.1:8000/user/users
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoiNjVkYzliOTdjNzBiNWRjOTVjY2EwNWZlIiwibmFtZSI6IlRlc3QgMSIsImxvY2F0aW9uIjoiQ2hlbm5haSIsInRpdGxlIjoiREVWRUxPUEVSIHcifSwiaWF0IjoxNzEyMjEyMjAzLCJleHAiOjE3MTIyMTU4MDN9.sjWKCxedJPbHlUDMep2KlVmoQVa42CyvKzvj-Yrz6DU

### login the user 
POST http://127.0.0.1:8000/user/login HTTP/1.1
content-type: application/json

{
    "name":"Test 1"
}

### get file
GET http://127.0.0.1:8000/get_file
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoiNjVkYzliOTdjNzBiNWRjOTVjY2EwNWZlIiwibmFtZSI6IlRlc3QgMSIsImxvY2F0aW9uIjoiQ2hlbm5haSIsInRpdGxlIjoiREVWRUxPUEVSIHcifSwiaWF0IjoxNzEyMTMyOTkyLCJleHAiOjE3MTIxMzY1OTJ9.r7pt1jG7p2GkAbbOuhkeVUmBqjVrU0QOXN70MMHV1M8

### get author profilec
GET http://127.0.0.1:8000/author/auther_profile/65e85db7625742abec542ca1 HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoiNjVkYzliOTdjNzBiNWRjOTVjY2EwNWZlIiwibmFtZSI6IlRlc3QgMSIsImxvY2F0aW9uIjoiQ2hlbm5haSIsInRpdGxlIjoiREVWRUxPUEVSIHcifSwiaWF0IjoxNzExMTI3Mzc4LCJleHAiOjE3MTExMzA5Nzh9.rKfwC2iSX-YcMhS7lP7b1qCeWOYegm3pSC2ENF0TecQ